In [2]:

import matplotlib.pyplot as plt
import numpy as np
from scipy import linalg
from IPython.display import HTML
from tools import create_animation
%config InlineBackend.figure_format = 'svg'

In [3]:

N = 100
np.set_printoptions(threshold=20)
print(M.shape)
print(M)

In [4]:
N = 100
M = np.array([
    [ 1, -1,  0],
    [-1,  2, -1],
    [ 0, -1,  1],
])
print(M.shape)
print(M)

(3, 3)
[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  1]]


In [5]:


eigenvalue, eigenvector = linalg.eigh(M)



In [6]:


###########################
# Your codes here.
# Plot eigenvalue.
###########################



In [7]:


###########################
# Your codes here.
# Plot frequency.
###########################



In [8]:


n1, n2 = 1, -3
###########################
# Your codes here.
# Plot eigenvector (displacement).
###########################



In [ ]:
# choose normal mode
n = -1

# position shift of n-th normal mode
xxs = eigenvector[:,n]

# frequency of n-th normal mode
w = np.sqrt(eigenvalue[n])

# enlarge the position shift to plot clearly
xxs = xxs*3

# frequency is fixed to a constsnt to plot clearly
w = 5

# positions that seperate atom from each other
xx0 = np.arange(0,N)*2

# time range
tt = np.linspace(0, 2*np.pi, 80)
xxt = np.sin(tt*w)

# position of time and shift; xx(t,s)
xxts = xx0 + np.tensordot(xxt, xxs, axes=0)